// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alpha': string;
  'banner': string;
  'corner': string;
  'more': string;
  'roadmap': string;
}
export const cssExports: CssExports;
export default cssExports;
