// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'behance': string;
  'blog': string;
  'dribbble': string;
  'facebook': string;
  'git-hub': string;
  'instagram': string;
  'link': string;
  'linked-in': string;
  'nav-bar': string;
  'nav-links': string;
  'skype': string;
  'social-links': string;
  'twitter': string;
}
export const cssExports: CssExports;
export default cssExports;
