language: node_js
node_js: stable
before_script:
- npm install -g gulp
script: gulp build --prod
deploy:
  provider: heroku
  api_key:
    secure: KQdztO9N45KyJyrX22pu/BzUzExXlRuyodfWX+xtgXJ1BFJmZ6pgAKR1y4khbPt/QI8pvx38UGkWgQ3be6gpZghI5+appafGN5Uj4iFy1yN868pvKKK1FQc9noXwvzCFL7qFXGJzW7jz76LQzlMoIHWJuKHbFStexW/xGIaIECREWsYftsgYkNIfcyf8kZWJjuPUDO0tMd3hJpIZE3kb9Brf03LRVjiPzsQWdvfu+nuaVz8ihcJPt5MyvdJ+j0BKdC7hkoyBV7/ZMNhvoKgA0f5VuGD7MbDmWsvQk3c88KQqyqjyng1moX+9Q3QWtV+WZ/WKYI/EYey8tfk3BoEutrptzv8EHrvAsKekNPxbpcIeuBSbdhOqyV879AGQnmK+BuhLHIF/dE4aCvjX3Hf7kUpK2j4HayfsIw3BWqiCubXIk6Kn5gnhQVKNoCeYQR4Dg05g4ckmCveCOWEK8jJmKTDmWaUNTBqfjIcs0ofeM4aAOG8ZokRLlC15i80GtYfVSctZBGzFJIc4a7bolLn7vhXmMbxKxs2u/8uRbQU5AUDbigUeF077ikSojlikc5OtnGRvQLSH0YVaEo0Cimg9N05TjDxdAHegU1bBXe1Bn+T6YvJKrHb7U2m91PzUPp5LQ+5NrPIbjfJM8l2Psy7Ng05eEsBzMgNnFZpl1Z+xLjg=
  app: alex-foxleigh-portfolio
  on:
    repo: foxleigh81/alex-foxleigh-portfolio
