// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'git-hub': string;
  'link': string;
  'nav-bar': string;
  'social-links': string;
}
export const cssExports: CssExports;
export default cssExports;
