# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: karthikiyengar/node-nightwatch
    parallelism: 1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install environment dependencies
          command: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - && sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && sudo apt-get update && sudo apt-get --fix-broken --only-upgrade install google-chrome-stable
      - run: 
          name: Installing Node packages
          command: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: 
          name: Creating a production build
          command: yarn build
      - run: mkdir test-reports
      - run: mkdir test-assets
      - run: 
          name: Running e2e tests
          command: ./node_modules/.bin/magellan --local_browsers chrome
