# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: karthikiyengar/node-nightwatch
    parallelism: 1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run:
        name: Install node 9.0.0 (need right version for `yarn`)
        command: |
          set +e             
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install v9.0.0
          nvm alias default v9.0.0
          echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
          echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
      - run: 
          name: Installing Node packages
          command: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: 
          name: Creating a production build
          command: yarn build
      - run: mkdir test-reports
      - run: mkdir test-assets
      - run: 
          name: Running e2e tests
          command: ./node_modules/.bin/magellan --local_browsers chrome
