// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mini-me': string;
  'w-narrow': string;
  'w-regular': string;
  'w-wide': string;
}
export const cssExports: CssExports;
export default cssExports;
