// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'darkness': string;
  'daylight': string;
  'salutation': string;
  'status-available': string;
  'status-container': string;
  'sunrise': string;
  'sunset': string;
}
export const cssExports: CssExports;
export default cssExports;
