// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'darkness': string;
  'daylight': string;
  'sunrise': string;
  'sunset': string;
}
export const cssExports: CssExports;
export default cssExports;
